spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://${URL:localhost:5432}/${DB_NAME:dmc}
    username: ${USER:postgres}
    password: ${PASS:postgres}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres


#url: jdbc:oracle:thin:@//${ORACLEDB_HOST}:${ORACLEDB_PORT}/${ORACLEDB_SERVICENAME}