spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://${DCM_DATASOURCE_HOST:localhost:5432}/${DCM_DATASOURCE_NAME:mydb}
    username: ${DCM_DATASOURCE_USER:postgres}
    password: ${DCM_DATASOURCE_PASS:postgres}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres


#url: jdbc:oracle:thin:@//${ORACLEDB_HOST}:${ORACLEDB_PORT}/${ORACLEDB_SERVICENAME}