# *******************************************************************************
# Copyright (c) 2023 BMW AG
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
#   See the NOTICE file(s) distributed with this work for additional
#   information regarding copyright ownership.
#
#   This program and the accompanying materials are made available under the
#   terms of the Apache License, Version 2.0 which is available at
#   https://www.apache.org/licenses/LICENSE-2.0.
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#
#   SPDX-License-Identifier: Apache-2.0
#   ********************************************************************************



tx-dcm-backend:

  springProfiles:
    - dev

  appName: tx-demand-capacity-mgmt-backend
  environment: dev

  image:
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "dev"

  ingress:
    enabled: true
    host: catenax-dcm-capacity-mgmt-dev.demo.catena-x.net

  certificate:
    host: "dcm-capacity-mgmt-backend.dev.demo.catena-x.net"

  configmap:
    # Specifies whether a configmap should be created or not
    data:
      spring_profiles_active: dev
      SECURITY_ENABLED: 'true'

postgres:
  auth:
    postgresPassword: <path:cgi-dcm-foss/value-added-service/data/dcm/dev/postgresql#postgres-password>
    password: <path:cgi-dcm-foss/value-added-service/data/dcm/dev/postgresql#password>